apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}
        role: {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.repository }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: services-info
          ports:
            - name: rspamd1
              containerPort: {{ .Values.port_0 }}
              protocol: TCP
            - name: rspam2
              containerPort: {{ .Values.port_2 }}
              protocol: TCP
            - name: rspam3
              containerPort: {{ .Values.port_2 }}
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    role: {{ .Values.name }}
  ports:
    - name: rspam1
      port: {{ .Values.port_0 }}
      targetPort: {{ .Values.port_0 }}
    - name: rspam2
      port: {{ .Values.port_1 }}
      targetPort: {{ .Values.port_1 }}
    - name: rspam3
      port: {{ .Values.port_2 }}
      targetPort: {{ .Values.port_2 }}
